/**
 * SYSTEMA — Phase 21 CLAP infrastructure tests.
 *
 * WHAT THIS ACTUALLY PROVES
 * -------------------------
 * Section 1 is a real numerical test. It runs a line-for-line port of
 * ClapMelFrontEnd.kt against a reference log-mel generated by librosa
 * 0.11.0 using LAION-CLAP's exact configuration, and asserts agreement
 * to 1e-3 dB. That is the difference between "the mel code looks
 * right" and "the mel code reproduces the library CLAP was trained
 * with". If the Kotlin drifts from the port, section 2 catches it by
 * pinning every constant in both files.
 *
 * The remaining sections are SOURCE-LEVEL SAFETY ASSERTIONS. They read
 * the Kotlin and Vue sources and check that the dangerous things are
 * absent and the required things are present. That is weaker than
 * executing them, and it is stated plainly here rather than implied
 * away: this suite CANNOT prove the model loads, that memory is
 * released, or that anything works on a device.
 *
 * NOT PROVEN HERE, AND NOT CLAIMED ANYWHERE:
 *   - that any CLAP model loads on a device
 *   - that ONNX Runtime accepts the tensor
 *   - that memory is genuinely released after unload
 *   - that the embedding is semantically meaningful
 *
 * Those require a device run with a real model, which has NOT been
 * performed.
 */

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { CLAP_HTSAT_TINY, hzToMel, logMel, melToHz } from './clap-melref/melPort'

const ROOT = resolve(import.meta.dirname, '..')
const read = (p: string) => readFileSync(resolve(ROOT, p), 'utf8')

let passed = 0
let failed = 0
const failures: string[] = []

function ok(name: string, condition: boolean, detail = '') {
  if (condition) passed++
  else {
    failed++
    failures.push(name)
    console.log(`  FAIL  ${name}${detail ? ` — ${detail}` : ''}`)
  }
}
function section(t: string) { console.log(`\n${t}`) }

const KOTLIN = 'android/app/src/main/java/com/systema/music/inference'
const frontEndSrc = read(`${KOTLIN}/clap/ClapMelFrontEnd.kt`)
const adapterSrc = read(`${KOTLIN}/clap/ClapAudioEmbeddingModel.kt`)
const sessionSrc = read(`${KOTLIN}/clap/ClapSession.kt`)
const logSrc = read(`${KOTLIN}/clap/ClapLog.kt`)
const guardSrc = read(`${KOTLIN}/MemoryGuard.kt`)
const ifaceSrc = read(`${KOTLIN}/AudioEmbeddingModel.kt`)
const pluginSrc = read(`${KOTLIN}/InferencePlugin.kt`)
const portSrc = read('scripts/clap-melref/melPort.ts')

// =====================================================================
section('1. Log-mel front end vs librosa (NUMERICAL)')
{
  const ref = JSON.parse(read('scripts/clap-melref/librosa-reference.json')) as {
    config: Record<string, number>
    input: number[]
    logmel: number[][]
  }

  // The fixture must describe CLAP's configuration, not some other one.
  ok('fixture is 48 kHz', ref.config.sampleRate === 48000)
  ok('fixture n_fft is 1024', ref.config.nFft === 1024)
  ok('fixture hop is 480', ref.config.hopSize === 480)
  ok('fixture has 64 mel bins', ref.config.melBins === 64)
  ok('fixture fmin is 50', ref.config.fMin === 50)
  ok('fixture fmax is 14000', ref.config.fMax === 14000)

  const mine = logMel(Float32Array.from(ref.input), CLAP_HTSAT_TINY)

  ok('mel bin count matches librosa', mine.length === ref.logmel.length,
    `${mine.length} vs ${ref.logmel.length}`)
  ok('frame count matches librosa',
    mine[0]!.length === ref.logmel[0]!.length,
    `${mine[0]!.length} vs ${ref.logmel[0]!.length}`)

  let maxDiff = 0
  let worst = ''
  for (let m = 0; m < ref.logmel.length; m++) {
    for (let t = 0; t < ref.logmel[m]!.length; t++) {
      const d = Math.abs(mine[m]![t]! - ref.logmel[m]![t]!)
      if (d > maxDiff) {
        maxDiff = d
        worst = `mel=${m} frame=${t} got=${mine[m]![t]} want=${ref.logmel[m]![t]}`
      }
    }
  }
  // 1e-3 dB is far tighter than any perceptual or model-relevant
  // threshold, and float32 rounding sits three orders below it.
  ok('log-mel matches librosa within 1e-3 dB', maxDiff < 1e-3,
    `max diff ${maxDiff.toExponential(3)} at ${worst}`)
  console.log(`       max deviation from librosa: ${maxDiff.toExponential(3)} dB`)

  // A reference that is all one value would make the comparison
  // vacuous, so confirm the fixture actually has structure.
  const flat = ref.logmel.flat()
  const spread = Math.max(...flat) - Math.min(...flat)
  ok('reference has real dynamic range', spread > 20, `spread ${spread.toFixed(1)} dB`)

  // Slaney mel scale round-trip and the documented break point.
  ok('hzToMel(1000) is the 15.0 break point', Math.abs(hzToMel(1000) - 15) < 1e-9)
  ok('melToHz(hzToMel(x)) round-trips at 440 Hz',
    Math.abs(melToHz(hzToMel(440)) - 440) < 1e-6)
  ok('melToHz(hzToMel(x)) round-trips at 8000 Hz',
    Math.abs(melToHz(hzToMel(8000)) - 8000) < 1e-6)
  ok('mel scale is linear below 1000 Hz',
    Math.abs(hzToMel(500) - 500 / (200 / 3)) < 1e-9)
}

// =====================================================================
section('2. Kotlin and the verified port declare identical constants')
{
  // Section 1 validated the PORT. These assertions are what tie that
  // result to the Kotlin that actually ships.
  ok('Kotlin sample rate 48000', /DEFAULT_SAMPLE_RATE\s*=\s*48_000/.test(frontEndSrc))
  ok('Kotlin window 1024', /DEFAULT_WINDOW_SIZE\s*=\s*1024/.test(frontEndSrc))
  ok('Kotlin hop 480', /DEFAULT_HOP_SIZE\s*=\s*480/.test(frontEndSrc))
  ok('Kotlin 64 mel bins', /DEFAULT_MEL_BINS\s*=\s*64/.test(frontEndSrc))
  ok('Kotlin fmin 50', /DEFAULT_FMIN\s*=\s*50f/.test(frontEndSrc))
  ok('Kotlin fmax 14000', /DEFAULT_FMAX\s*=\s*14_000f/.test(frontEndSrc))
  ok('Kotlin clip 480000 samples (10 s)',
    /DEFAULT_CLIP_SAMPLES\s*=\s*480_000/.test(frontEndSrc))
  ok('Kotlin amin 1e-10', /AMIN\s*=\s*1e-10f/.test(frontEndSrc))

  // The Slaney break point and log step, which are what make this the
  // librosa scale rather than the HTK one.
  ok('Kotlin Slaney break at 1000 Hz', /MIN_LOG_HZ\s*=\s*1000\.0/.test(frontEndSrc))
  ok('Kotlin Slaney break at mel 15', /MIN_LOG_MEL\s*=\s*15\.0/.test(frontEndSrc))
  ok('Kotlin log step is ln(6.4)/27',
    frontEndSrc.includes('0.06875177742094912'))
  ok('port uses the same log step', portSrc.includes('0.06875177742094912'))

  // Power, not magnitude — torchlibrosa squares the STFT.
  ok('Kotlin uses a POWER spectrogram', /mag\s*\*\s*mag/.test(frontEndSrc))
  ok('Kotlin uses 10*log10, not 20*log10', /10\.0f?\s*\*\s*log10|10\s*\*\s*log10/.test(frontEndSrc))
  // Careful: "top_db" appears in the comments that document its
  // ABSENCE, so match on code rather than on the whole file.
  ok('Kotlin applies no top_db clamp',
    !/coerceAtLeast\(\s*max\w*\s*-/.test(frontEndSrc) &&
    !/\.coerceIn\(/.test(frontEndSrc) &&
    frontEndSrc.includes('top_db=None'))
  // Slaney area normalisation.
  ok('Kotlin area-normalises the filters', /enorm|2\.0\s*\/\s*\(upper/.test(frontEndSrc))
  ok('Kotlin reflect-pads rather than zero-pads', /reflectSample/.test(frontEndSrc))
}

// =====================================================================
section('3. Memory guard refuses rather than guessing (§4)')
{
  ok('guard exists', guardSrc.includes('object MemoryGuard'))
  ok('guard exposes evaluate()', /fun evaluate\(/.test(guardSrc))
  ok('guard reads ActivityManager.MemoryInfo', guardSrc.includes('ActivityManager'))
  ok('guard honours the system lowMemory flag', guardSrc.includes('lowMemory'))

  // The important behaviour: an unreadable memory counter must REFUSE,
  // not shrug and continue. Proceeding blind is how a device freezes.
  ok('unreadable memory is a refusal', guardSrc.includes('MEMORY_UNREADABLE'))
  ok('has an absolute floor', guardSrc.includes('BELOW_ABSOLUTE_FLOOR'))
  ok('has an insufficient-memory reason', guardSrc.includes('INSUFFICIENT_MEMORY'))
  ok('has a low-memory reason', guardSrc.includes('SYSTEM_LOW_MEMORY'))
  ok('accounts for more than the file size',
    guardSrc.includes('MODEL_RESIDENT_FACTOR'))
  ok('requires headroom beyond the estimate',
    guardSrc.includes('REQUIRED_HEADROOM_MB'))
  // Honesty: the estimate is a heuristic and must say so.
  ok('carries an explicit caveat', guardSrc.includes('caveat'))

  ok('the load path consults the guard',
    sessionSrc.includes('MemoryGuard.evaluate'))
  ok('a refusal aborts the load',
    /if\s*\(!decision\.allowed\)/.test(sessionSrc) &&
    sessionSrc.includes('Refusing to load'))
}

// =====================================================================
section('4. Bounded windows and incremental aggregation (§4)')
{
  ok('window count is capped', adapterSrc.includes('DEFAULT_MAX_WINDOWS'))
  ok('the cap is small', /DEFAULT_MAX_WINDOWS\s*=\s*[1-9]\b/.test(adapterSrc))
  ok('windows overlap 50%', /WINDOW_STRIDE_DIVISOR\s*=\s*2/.test(adapterSrc))
  ok('accumulates into a single running sum',
    /var sum: DoubleArray\?/.test(adapterSrc))
  ok('per-window buffers are not retained',
    !/frameEmbeddings|allWindows|windowTensors/.test(adapterSrc))
  ok('the session decodes a bounded amount of audio',
    sessionSrc.includes('MAX_TEST_AUDIO_MS'))
  ok('decoded chunks are released after concatenation',
    sessionSrc.includes('chunks.clear()'))

  // Mean-pool then L2, with no fabricated unit vector.
  ok('mean-pools across windows', /acc\[it\]\s*\/\s*windowsProcessed/.test(adapterSrc))
  ok('L2 normalises', adapterSrc.includes('preNormL2'))
  ok('refuses to fabricate a unit vector from a zero vector',
    adapterSrc.includes('Do not fabricate a unit vector'))
}

// =====================================================================
section('5. One session only (§4)')
{
  ok('adapter refuses a second load',
    adapterSrc.includes('A CLAP session is already loaded'))
  ok('adapter refuses when the runtime already holds a session',
    adapterSrc.includes('The runtime already holds a session'))
  ok('session refuses to replace a live model',
    sessionSrc.includes('Release it '))
  ok('access is serialised by a mutex',
    adapterSrc.includes('Mutex()') && sessionSrc.includes('Mutex()'))
  ok('unload never throws', adapterSrc.includes('override suspend fun unload'))
}

// =====================================================================
section('6. The single-track gate (§5)')
{
  // The native method takes ONE trackId and ONE uri. A signature that
  // cannot express a batch is a stronger guarantee than a length check.
  ok('native exposes clapTestOneTrack', pluginSrc.includes('fun clapTestOneTrack'))
  ok('it takes a single trackId', pluginSrc.includes('call.getString("trackId")'))
  ok('it takes a single uri', pluginSrc.includes('call.getString("uri")'))
  ok('it accepts no tracks array',
    !/clapTestOneTrack[\s\S]{0,900}getArray\("tracks"/.test(pluginSrc))
  ok('both arguments are required',
    pluginSrc.includes('Both trackId and uri are required'))

  ok('multi-track starts locked',
    /multiTrackUnlocked\s*=\s*false/.test(sessionSrc))
  ok('only a valid result unlocks multi-track',
    /if\s*\(outputValid\)[\s\S]{0,300}multiTrackUnlocked\s*=\s*true/.test(sessionSrc))
  ok('an unvalidated model is refused a real track',
    sessionSrc.includes('has not passed validation'))
}

// =====================================================================
section('7. Validation happens before inference (§2)')
{
  ok('validate() exists on the interface', ifaceSrc.includes('suspend fun validate'))
  ok('checks the graph has inputs and outputs',
    adapterSrc.includes('graph has inputs and outputs'))
  ok('checks the sample rate is known',
    adapterSrc.includes('required sample rate is known'))
  ok('checks the output is finite', adapterSrc.includes('output is finite'))
  ok('checks the output is normalizable',
    /normalisable|normalizable/.test(adapterSrc))
  ok('probes with a tone, not silence',
    adapterSrc.includes('Silence could produce'))
  ok('reports the actual technical reason',
    adapterSrc.includes('failureMessage') && adapterSrc.includes('javaClass.simpleName'))
  ok('validation failure is not silently swallowed',
    !/catch\s*\([^)]*\)\s*\{\s*\}/.test(adapterSrc))
}

// =====================================================================
section('8. Text embedding is declared but not faked (§7)')
{
  ok('embedText is on the interface', ifaceSrc.includes('embedText'))
  // The default must THROW. Returning a plausible-looking vector from
  // a model with no text tower is the worst possible outcome: it would
  // silently poison a shared-space comparison.
  ok('the default implementation throws', /embedText[\s\S]{0,400}throw/.test(ifaceSrc))
  ok('supportsText defaults to false', /supportsText\(\):\s*Boolean\s*=\s*false/.test(ifaceSrc))
  // Capability is read off the loaded graph, not guessed from a name.
  ok('text support is detected from graph inputs',
    /loadedInputNames[\s\S]{0,200}input_ids|input_ids[\s\S]{0,200}loadedInputNames/
      .test(adapterSrc))
  ok('text support is NOT inferred from the family string',
    !/supportsText[\s\S]{0,200}FAMILY/.test(adapterSrc))
}

// =====================================================================
section('9. Structured diagnostics, no raw audio (§9)')
{
  for (const ev of [
    'IMPORT', 'VALIDATE', 'LOAD_START', 'LOAD_SUCCESS', 'INFERENCE_START',
    'INFERENCE_END', 'EMBEDDING_VALID', 'UNLOAD_START', 'UNLOAD_SUCCESS',
    'MEMORY_BEFORE', 'MEMORY_AFTER',
  ]) {
    ok(`logs ${ev}`, new RegExp(`const val ${ev}\\b`).test(logSrc))
  }
  ok('tagged [CLAP]', logSrc.includes('[CLAP]'))

  // Every failure diagnostic is a NAMED parameter, so no call site can
  // quietly omit half of them.
  for (const f of [
    'throwable', 'modelId', 'modelSizeBytes', 'inputShape', 'inputType',
    'sampleRate', 'audioDurationSec', 'memoryBeforeKb', 'memoryAfterKb',
  ]) {
    ok(`failure() requires ${f}`, new RegExp(`${f}:`).test(logSrc))
  }

  // No overload may accept a sample buffer.
  ok('no logging path accepts raw audio',
    !/fun \w+\([^)]*FloatArray/.test(logSrc))
  ok('raw audio is never logged', !/samples\.joinToString|pcm\.joinToString/.test(logSrc))
}

// =====================================================================
section('10. PlayerEngine isolation (§8)')
{
  const player = read('android/app/src/main/java/com/systema/music/player/PlayerEngine.kt')
  ok('PlayerEngine does not reference CLAP', !/[Cc]lap/.test(player))
  ok('PlayerEngine does not import the inference package',
    !player.includes('com.systema.music.inference'))

  // And the reverse: the CLAP subsystem must not reach into playback.
  for (const [name, src] of [
    ['adapter', adapterSrc], ['session', sessionSrc],
    ['front end', frontEndSrc], ['guard', guardSrc],
  ] as const) {
    ok(`${name} does not touch the player`, !src.includes('com.systema.music.player'))
  }
}

// =====================================================================
section('11. Nothing runs automatically (§4, §11)')
{
  // Every CLAP entry point must be an explicit @PluginMethod.
  for (const m of [
    'getClapStatus', 'clapMemoryCheck', 'clapLoadModel',
    'clapValidateModel', 'clapTestOneTrack', 'clapRelease',
  ]) {
    const re = new RegExp(`@PluginMethod\\s+fun ${m}\\(`)
    ok(`${m} is an explicit plugin method`, re.test(pluginSrc))
  }
  // The session must not schedule its own work.
  ok('session starts no coroutine of its own',
    !/GlobalScope|scope\.launch|CoroutineScope\(/.test(sessionSrc))
  ok('session registers no lifecycle observer',
    !/Observer|LiveData|WorkManager|Handler\(/.test(sessionSrc))
  ok('import does not chain into inference',
    !/handleModelPicked[\s\S]{0,600}clapLoadModel/.test(pluginSrc))
  ok('the model is built lazily', pluginSrc.includes('by lazy { ClapSession'))
}

// =====================================================================
section('12. No weights, no downloads (§11)')
{
  for (const [name, src] of [
    ['adapter', adapterSrc], ['session', sessionSrc], ['guard', guardSrc],
    ['front end', frontEndSrc], ['interface', ifaceSrc],
  ] as const) {
    ok(`${name} performs no network access`,
      !/HttpURLConnection|OkHttp|URL\(|http:\/\/|https:\/\//.test(src))
  }
  const page = read('app/pages/dev/ai-benchmark/clap.vue')
  ok('the UI performs no download', !/fetch\(|axios|XMLHttpRequest/.test(page))
  ok('the UI says nothing is downloaded automatically',
    /nothing\s+is\s+ever\s+downloaded/.test(page.replace(/\s+/g, ' ')))
}

// =====================================================================
section('13. No automatic production selection (§10)')
{
  ok('status is never PRODUCTION from code',
    !/status\s*=\s*"PRODUCTION"|PRODUCTION_SELECTED\s*=\s*true/.test(sessionSrc))
  ok('device-tested is the ceiling', sessionSrc.includes('DEVICE_TESTED'))
  ok('markDeviceTested does not mark production',
    /markDeviceTested[\s\S]{0,400}DEVICE_TESTED/.test(adapterSrc))
  ok('status reports productionSelected=false',
    sessionSrc.includes('put("productionSelected", false)'))
  ok('the note names it a human decision',
    sessionSrc.includes('explicit human decision'))
  const page = read('app/pages/dev/ai-benchmark/clap.vue')
  ok('the UI states no production model is chosen',
    page.includes('NO PRODUCTION MODEL HAS BEEN CHOSEN'))
}

// =====================================================================
section('14. Import records a real identity (§1)')
{
  const importer = read(`${KOTLIN}/ModelImporter.kt`)
  ok('import records SHA-256', importer.includes('val sha256 = storage.checksum'))
  ok('import records a timestamp', importer.includes('importedAt'))
  ok('both cross the bridge',
    importer.includes('put("sha256"') && importer.includes('put("importedAt"'))

  const contract = read('app/services/native/inferencePlugin.ts')
  ok('TS exposes sha256 on the import result', /sha256\?:\s*string/.test(contract))
  ok('TS exposes importedAt', /importedAt\?:\s*number/.test(contract))
}

// =====================================================================
section('15. The tensor shape is declared, not left to a default')
{
  // The runtime builds its ONNX tensor from the DESCRIPTOR's shape. An
  // imported model defaults to [-1], which would submit a 4-D log-mel
  // as a flat vector. The session must override that.
  ok('the session declares a 4-D input shape',
    /listOf\(1L,\s*1L,\s*frames\.toLong\(\),/.test(sessionSrc))
  ok('it declares LOG_MEL_SPECTROGRAM',
    sessionSrc.includes('InputFormat.LOG_MEL_SPECTROGRAM'))
  ok('it declares the CLAP sample rate',
    sessionSrc.includes('sampleRate = frontEndSampleRate'))
  ok('the tensor layout is time-major',
    frontEndSrc.includes('fun toNchwTimeMajor'))

  // 480000/480 + 1 = 1001 frames x 64 mels.
  const frames = 480000 / 480 + 1
  ok('frame count arithmetic is 1001', frames === 1001)
  ok('tensor element count is 64064', frames * 64 === 64064)

  // The decoder must be asked for 48 kHz, not the DSP default 22050.
  ok('the session decodes at the model rate',
    sessionSrc.includes('targetSampleRate = frontEndSampleRate'))
  ok('the source rate is not mistaken for the decoded rate',
    sessionSrc.includes('NOT info.sourceSampleRate'))
}

// =====================================================================
section('16. Quality-lab compatibility is not disturbed (§6)')
{
  // Phase 20 fixed pair identity. Nothing in this phase may regress it.
  const mapping = read('app/services/ai-lab/reportMapping.ts')
  ok('canonical pair ids still present', mapping.includes('trackIdA'))
  ok('the labelled lab still uses the mapper',
    read('app/pages/dev/ai-benchmark/labeled.vue')
      .includes("from '~/services/ai-lab/reportMapping'"))
  ok('CLAP did not fork a new lab system',
    !read('app/pages/dev/ai-benchmark/clap.vue').includes('pairResults'))
}

console.log(`\n${'='.repeat(60)}`)
console.log(`CLAP INFRASTRUCTURE — ${passed} passed, ${failed} failed`)
if (failed > 0) {
  console.log('\nFailures:')
  for (const f of failures) console.log(`  - ${f}`)
  process.exit(1)
}
console.log('All CLAP infrastructure tests passed.')
console.log(
  '\nNOT PROVEN HERE: that a CLAP model loads on a device, that ORT\n' +
  'accepts the tensor, that memory is released, or that the embedding\n' +
  'is meaningful. Those need a device run, which has NOT happened.',
)
