/**
 * SYSTEMA — Phase 21 CLAP infrastructure tests.
 *
 * WHAT THIS ACTUALLY PROVES
 * -------------------------
 * Section 1 is a real numerical test. It runs a line-for-line port of
 * ClapMelFrontEnd.kt against a reference log-mel generated by librosa
 * 0.11.0 using LAION-CLAP's exact configuration, and asserts agreement
 * to 1e-3 dB. That is the difference between "the mel code looks
 * right" and "the mel code reproduces the library CLAP was trained
 * with". If the Kotlin drifts from the port, section 2 catches it by
 * pinning every constant in both files.
 *
 * The remaining sections are SOURCE-LEVEL SAFETY ASSERTIONS. They read
 * the Kotlin and Vue sources and check that the dangerous things are
 * absent and the required things are present. That is weaker than
 * executing them, and it is stated plainly here rather than implied
 * away: this suite CANNOT prove the model loads, that memory is
 * released, or that anything works on a device.
 *
 * NOT PROVEN HERE, AND NOT CLAIMED ANYWHERE:
 *   - that any CLAP model loads on a device
 *   - that ONNX Runtime accepts the tensor
 *   - that memory is genuinely released after unload
 *   - that the embedding is semantically meaningful
 *
 * Those require a device run with a real model, which has NOT been
 * performed.
 */

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { CLAP_HTSAT_TINY, hzToMel, logMel, melToHz } from './clap-melref/melPort'
import { derive } from './clap-melref/graphContractPort'
import { coverageSec, runStream, windowBudget } from './clap-melref/streamingPort'
import {
  ShapeMismatchError,
  elementCount,
  fixedWindowSamplesFor,
  resolveShape,
  windowLengths,
} from './clap-melref/tensorShapePort'

const ROOT = resolve(import.meta.dirname, '..')
const read = (p: string) => readFileSync(resolve(ROOT, p), 'utf8')

let passed = 0
let failed = 0
const failures: string[] = []

function ok(name: string, condition: boolean, detail = '') {
  if (condition) passed++
  else {
    failed++
    failures.push(name)
    console.log(`  FAIL  ${name}${detail ? ` — ${detail}` : ''}`)
  }
}
function section(t: string) { console.log(`\n${t}`) }

const KOTLIN = 'android/app/src/main/java/com/systema/music/inference'
const frontEndSrc = read(`${KOTLIN}/clap/ClapMelFrontEnd.kt`)
const adapterSrc = read(`${KOTLIN}/clap/ClapAudioEmbeddingModel.kt`)
const sessionSrc = read(`${KOTLIN}/clap/ClapSession.kt`)
const logSrc = read(`${KOTLIN}/clap/ClapLog.kt`)
const guardSrc = read(`${KOTLIN}/MemoryGuard.kt`)
const contractSrc = read(`${KOTLIN}/clap/ClapGraphContract.kt`)
const ifaceSrc = read(`${KOTLIN}/AudioEmbeddingModel.kt`)
const pluginSrc = read(`${KOTLIN}/InferencePlugin.kt`)
const portSrc = read('scripts/clap-melref/melPort.ts')

// =====================================================================
section('1. Log-mel front end vs librosa (NUMERICAL)')
{
  const ref = JSON.parse(read('scripts/clap-melref/librosa-reference.json')) as {
    config: Record<string, number>
    input: number[]
    logmel: number[][]
  }

  // The fixture must describe CLAP's configuration, not some other one.
  ok('fixture is 48 kHz', ref.config.sampleRate === 48000)
  ok('fixture n_fft is 1024', ref.config.nFft === 1024)
  ok('fixture hop is 480', ref.config.hopSize === 480)
  ok('fixture has 64 mel bins', ref.config.melBins === 64)
  ok('fixture fmin is 50', ref.config.fMin === 50)
  ok('fixture fmax is 14000', ref.config.fMax === 14000)

  const mine = logMel(Float32Array.from(ref.input), CLAP_HTSAT_TINY)

  ok('mel bin count matches librosa', mine.length === ref.logmel.length,
    `${mine.length} vs ${ref.logmel.length}`)
  ok('frame count matches librosa',
    mine[0]!.length === ref.logmel[0]!.length,
    `${mine[0]!.length} vs ${ref.logmel[0]!.length}`)

  let maxDiff = 0
  let worst = ''
  for (let m = 0; m < ref.logmel.length; m++) {
    for (let t = 0; t < ref.logmel[m]!.length; t++) {
      const d = Math.abs(mine[m]![t]! - ref.logmel[m]![t]!)
      if (d > maxDiff) {
        maxDiff = d
        worst = `mel=${m} frame=${t} got=${mine[m]![t]} want=${ref.logmel[m]![t]}`
      }
    }
  }
  // 1e-3 dB is far tighter than any perceptual or model-relevant
  // threshold, and float32 rounding sits three orders below it.
  ok('log-mel matches librosa within 1e-3 dB', maxDiff < 1e-3,
    `max diff ${maxDiff.toExponential(3)} at ${worst}`)
  console.log(`       max deviation from librosa: ${maxDiff.toExponential(3)} dB`)

  // A reference that is all one value would make the comparison
  // vacuous, so confirm the fixture actually has structure.
  const flat = ref.logmel.flat()
  const spread = Math.max(...flat) - Math.min(...flat)
  ok('reference has real dynamic range', spread > 20, `spread ${spread.toFixed(1)} dB`)

  // Slaney mel scale round-trip and the documented break point.
  ok('hzToMel(1000) is the 15.0 break point', Math.abs(hzToMel(1000) - 15) < 1e-9)
  ok('melToHz(hzToMel(x)) round-trips at 440 Hz',
    Math.abs(melToHz(hzToMel(440)) - 440) < 1e-6)
  ok('melToHz(hzToMel(x)) round-trips at 8000 Hz',
    Math.abs(melToHz(hzToMel(8000)) - 8000) < 1e-6)
  ok('mel scale is linear below 1000 Hz',
    Math.abs(hzToMel(500) - 500 / (200 / 3)) < 1e-9)
}

// =====================================================================
section('2. Kotlin and the verified port declare identical constants')
{
  // Section 1 validated the PORT. These assertions are what tie that
  // result to the Kotlin that actually ships.
  ok('Kotlin sample rate 48000', /DEFAULT_SAMPLE_RATE\s*=\s*48_000/.test(frontEndSrc))
  ok('Kotlin window 1024', /DEFAULT_WINDOW_SIZE\s*=\s*1024/.test(frontEndSrc))
  ok('Kotlin hop 480', /DEFAULT_HOP_SIZE\s*=\s*480/.test(frontEndSrc))
  ok('Kotlin 64 mel bins', /DEFAULT_MEL_BINS\s*=\s*64/.test(frontEndSrc))
  ok('Kotlin fmin 50', /DEFAULT_FMIN\s*=\s*50f/.test(frontEndSrc))
  ok('Kotlin fmax 14000', /DEFAULT_FMAX\s*=\s*14_000f/.test(frontEndSrc))
  ok('Kotlin clip 480000 samples (10 s)',
    /DEFAULT_CLIP_SAMPLES\s*=\s*480_000/.test(frontEndSrc))
  ok('Kotlin amin 1e-10', /AMIN\s*=\s*1e-10f/.test(frontEndSrc))

  // The Slaney break point and log step, which are what make this the
  // librosa scale rather than the HTK one.
  ok('Kotlin Slaney break at 1000 Hz', /MIN_LOG_HZ\s*=\s*1000\.0/.test(frontEndSrc))
  ok('Kotlin Slaney break at mel 15', /MIN_LOG_MEL\s*=\s*15\.0/.test(frontEndSrc))
  ok('Kotlin log step is ln(6.4)/27',
    frontEndSrc.includes('0.06875177742094912'))
  ok('port uses the same log step', portSrc.includes('0.06875177742094912'))

  // Power, not magnitude — torchlibrosa squares the STFT.
  ok('Kotlin uses a POWER spectrogram', /mag\s*\*\s*mag/.test(frontEndSrc))
  ok('Kotlin uses 10*log10, not 20*log10', /10\.0f?\s*\*\s*log10|10\s*\*\s*log10/.test(frontEndSrc))
  // Careful: "top_db" appears in the comments that document its
  // ABSENCE, so match on code rather than on the whole file.
  ok('Kotlin applies no top_db clamp',
    !/coerceAtLeast\(\s*max\w*\s*-/.test(frontEndSrc) &&
    !/\.coerceIn\(/.test(frontEndSrc) &&
    frontEndSrc.includes('top_db=None'))
  // Slaney area normalisation.
  ok('Kotlin area-normalises the filters', /enorm|2\.0\s*\/\s*\(upper/.test(frontEndSrc))
  ok('Kotlin reflect-pads rather than zero-pads', /reflectSample/.test(frontEndSrc))
}

// =====================================================================
section('3. Memory guard refuses rather than guessing (§4)')
{
  ok('guard exists', guardSrc.includes('object MemoryGuard'))
  ok('guard exposes evaluate()', /fun evaluate\(/.test(guardSrc))
  ok('guard reads ActivityManager.MemoryInfo', guardSrc.includes('ActivityManager'))
  ok('guard honours the system lowMemory flag', guardSrc.includes('lowMemory'))

  // The important behaviour: an unreadable memory counter must REFUSE,
  // not shrug and continue. Proceeding blind is how a device freezes.
  ok('unreadable memory is a refusal', guardSrc.includes('MEMORY_UNREADABLE'))
  ok('has an absolute floor', guardSrc.includes('BELOW_ABSOLUTE_FLOOR'))
  ok('has an insufficient-memory reason', guardSrc.includes('INSUFFICIENT_MEMORY'))
  ok('has a low-memory reason', guardSrc.includes('SYSTEM_LOW_MEMORY'))
  ok('accounts for more than the file size',
    guardSrc.includes('MODEL_RESIDENT_FACTOR'))
  ok('requires headroom beyond the estimate',
    guardSrc.includes('REQUIRED_HEADROOM_MB'))
  // Honesty: the estimate is a heuristic and must say so.
  ok('carries an explicit caveat', guardSrc.includes('caveat'))

  ok('the load path consults the guard',
    sessionSrc.includes('MemoryGuard.evaluate'))
  ok('a refusal aborts the load',
    /if\s*\(!decision\.allowed\)/.test(sessionSrc) &&
    sessionSrc.includes('Refusing to load'))
}

// =====================================================================
section('4. Bounded windows and incremental aggregation (§4)')
{
  ok('window count is capped', adapterSrc.includes('DEFAULT_MAX_WINDOWS'))
  ok('the cap is small', /DEFAULT_MAX_WINDOWS\s*=\s*[1-9]\b/.test(adapterSrc))
  ok('windows overlap 50%', /WINDOW_STRIDE_DIVISOR\s*=\s*2/.test(adapterSrc))
  ok('accumulates into a single running sum',
    /var sum: DoubleArray\?/.test(adapterSrc))
  ok('per-window buffers are not retained',
    !/frameEmbeddings|allWindows|windowTensors/.test(adapterSrc))
  // Superseded by streaming: the decode is now bounded by the window
  // budget and the rendezvous channel, not by a byte cap on a buffer
  // that was accumulated in full.
  ok('the session bounds decoding by the window budget',
    /decodeCapMs/.test(sessionSrc))
  ok('a capped run stops the decoder instead of over-decoding',
    /shouldCancel = \{ stream\.isSaturated\(\) \}/.test(sessionSrc))

  // Mean-pool then L2, with no fabricated unit vector.
  ok('mean-pools across windows', /acc\[it\]\s*\/\s*windowsProcessed/.test(adapterSrc))
  ok('L2 normalises', adapterSrc.includes('preNormL2'))
  ok('refuses to fabricate a unit vector from a zero vector',
    adapterSrc.includes('Do not fabricate a unit vector'))
}

// =====================================================================
section('5. One session only (§4)')
{
  ok('adapter refuses a second load',
    adapterSrc.includes('A CLAP session is already loaded'))
  ok('adapter refuses when the runtime already holds a session',
    adapterSrc.includes('The runtime already holds a session'))
  ok('session refuses to replace a live model',
    sessionSrc.includes('Release it '))
  ok('access is serialised by a mutex',
    adapterSrc.includes('Mutex()') && sessionSrc.includes('Mutex()'))
  ok('unload never throws', adapterSrc.includes('override suspend fun unload'))
}

// =====================================================================
section('6. The single-track gate (§5)')
{
  // The native method takes ONE trackId and ONE uri. A signature that
  // cannot express a batch is a stronger guarantee than a length check.
  ok('native exposes clapTestOneTrack', pluginSrc.includes('fun clapTestOneTrack'))
  ok('it takes a single trackId', pluginSrc.includes('call.getString("trackId")'))
  ok('it takes a single uri', pluginSrc.includes('call.getString("uri")'))
  ok('it accepts no tracks array',
    !/clapTestOneTrack[\s\S]{0,900}getArray\("tracks"/.test(pluginSrc))
  ok('both arguments are required',
    pluginSrc.includes('Both trackId and uri are required'))

  ok('multi-track starts locked',
    /multiTrackUnlocked\s*=\s*false/.test(sessionSrc))
  ok('only a valid result unlocks multi-track',
    /if\s*\(outputValid\)[\s\S]{0,300}multiTrackUnlocked\s*=\s*true/.test(sessionSrc))
  ok('an unvalidated model is refused a real track',
    sessionSrc.includes('has not passed validation'))
}

// =====================================================================
section('7. Validation happens before inference (§2)')
{
  ok('validate() exists on the interface', ifaceSrc.includes('suspend fun validate'))
  ok('checks the graph has inputs and outputs',
    adapterSrc.includes('graph has inputs and outputs'))
  ok('checks the sample rate is known',
    adapterSrc.includes('required sample rate is known'))
  ok('checks the output is finite', adapterSrc.includes('output is finite'))
  ok('checks the output is normalizable',
    /normalisable|normalizable/.test(adapterSrc))
  ok('probes with a tone, not silence',
    adapterSrc.includes('Silence could produce'))
  ok('reports the actual technical reason',
    adapterSrc.includes('failureMessage') && adapterSrc.includes('javaClass.simpleName'))
  ok('validation failure is not silently swallowed',
    !/catch\s*\([^)]*\)\s*\{\s*\}/.test(adapterSrc))
}

// =====================================================================
section('8. Text embedding is declared but not faked (§7)')
{
  ok('embedText is on the interface', ifaceSrc.includes('embedText'))
  // The default must THROW. Returning a plausible-looking vector from
  // a model with no text tower is the worst possible outcome: it would
  // silently poison a shared-space comparison.
  ok('the default implementation throws', /embedText[\s\S]{0,400}throw/.test(ifaceSrc))
  ok('supportsText defaults to false', /supportsText\(\):\s*Boolean\s*=\s*false/.test(ifaceSrc))
  // Capability is read off the loaded graph, not guessed from a name.
  ok('text support is detected from graph inputs',
    /loadedInputNames[\s\S]{0,200}input_ids|input_ids[\s\S]{0,200}loadedInputNames/
      .test(adapterSrc))
  ok('text support is NOT inferred from the family string',
    !/supportsText[\s\S]{0,200}FAMILY/.test(adapterSrc))
}

// =====================================================================
section('9. Structured diagnostics, no raw audio (§9)')
{
  for (const ev of [
    'IMPORT', 'VALIDATE', 'LOAD_START', 'LOAD_SUCCESS', 'INFERENCE_START',
    'INFERENCE_END', 'EMBEDDING_VALID', 'UNLOAD_START', 'UNLOAD_SUCCESS',
    'MEMORY_BEFORE', 'MEMORY_AFTER',
  ]) {
    ok(`logs ${ev}`, new RegExp(`const val ${ev}\\b`).test(logSrc))
  }
  ok('tagged [CLAP]', logSrc.includes('[CLAP]'))

  // Every failure diagnostic is a NAMED parameter, so no call site can
  // quietly omit half of them.
  for (const f of [
    'throwable', 'modelId', 'modelSizeBytes', 'inputShape', 'inputType',
    'sampleRate', 'audioDurationSec', 'memoryBeforeKb', 'memoryAfterKb',
  ]) {
    ok(`failure() requires ${f}`, new RegExp(`${f}:`).test(logSrc))
  }

  // No overload may accept a sample buffer.
  ok('no logging path accepts raw audio',
    !/fun \w+\([^)]*FloatArray/.test(logSrc))
  ok('raw audio is never logged', !/samples\.joinToString|pcm\.joinToString/.test(logSrc))
}

// =====================================================================
section('10. PlayerEngine isolation (§8)')
{
  const player = read('android/app/src/main/java/com/systema/music/player/PlayerEngine.kt')
  ok('PlayerEngine does not reference CLAP', !/[Cc]lap/.test(player))
  ok('PlayerEngine does not import the inference package',
    !player.includes('com.systema.music.inference'))

  // And the reverse: the CLAP subsystem must not reach into playback.
  for (const [name, src] of [
    ['adapter', adapterSrc], ['session', sessionSrc],
    ['front end', frontEndSrc], ['guard', guardSrc],
  ] as const) {
    ok(`${name} does not touch the player`, !src.includes('com.systema.music.player'))
  }
}

// =====================================================================
section('11. Nothing runs automatically (§4, §11)')
{
  // Every CLAP entry point must be an explicit @PluginMethod.
  for (const m of [
    'getClapStatus', 'clapMemoryCheck', 'clapLoadModel',
    'clapValidateModel', 'clapTestOneTrack', 'clapRelease',
  ]) {
    const re = new RegExp(`@PluginMethod\\s+fun ${m}\\(`)
    ok(`${m} is an explicit plugin method`, re.test(pluginSrc))
  }
  // The session must not schedule its own work.
  ok('session starts no coroutine of its own',
    !/GlobalScope|scope\.launch|CoroutineScope\(/.test(sessionSrc))
  ok('session registers no lifecycle observer',
    !/Observer|LiveData|WorkManager|Handler\(/.test(sessionSrc))
  ok('import does not chain into inference',
    !/handleModelPicked[\s\S]{0,600}clapLoadModel/.test(pluginSrc))
  ok('the model is built lazily', pluginSrc.includes('by lazy { ClapSession'))
}

// =====================================================================
section('12. No weights, no downloads (§11)')
{
  for (const [name, src] of [
    ['adapter', adapterSrc], ['session', sessionSrc], ['guard', guardSrc],
    ['front end', frontEndSrc], ['interface', ifaceSrc],
  ] as const) {
    ok(`${name} performs no network access`,
      !/HttpURLConnection|OkHttp|URL\(|http:\/\/|https:\/\//.test(src))
  }
  const page = read('app/pages/dev/ai-benchmark/clap.vue')
  ok('the UI performs no download', !/fetch\(|axios|XMLHttpRequest/.test(page))
  ok('the UI says nothing is downloaded automatically',
    /nothing\s+is\s+ever\s+downloaded/.test(page.replace(/\s+/g, ' ')))
}

// =====================================================================
section('13. No automatic production selection (§10)')
{
  ok('status is never PRODUCTION from code',
    !/status\s*=\s*"PRODUCTION"|PRODUCTION_SELECTED\s*=\s*true/.test(sessionSrc))
  ok('device-tested is the ceiling', sessionSrc.includes('DEVICE_TESTED'))
  ok('markDeviceTested does not mark production',
    /markDeviceTested[\s\S]{0,400}DEVICE_TESTED/.test(adapterSrc))
  ok('status reports productionSelected=false',
    sessionSrc.includes('put("productionSelected", false)'))
  ok('the note names it a human decision',
    sessionSrc.includes('explicit human decision'))
  const page = read('app/pages/dev/ai-benchmark/clap.vue')
  ok('the UI states no production model is chosen',
    page.includes('NO PRODUCTION MODEL HAS BEEN CHOSEN'))
}

// =====================================================================
section('14. Import records a real identity (§1)')
{
  const importer = read(`${KOTLIN}/ModelImporter.kt`)
  ok('import records SHA-256', importer.includes('val sha256 = storage.checksum'))
  ok('import records a timestamp', importer.includes('importedAt'))
  ok('both cross the bridge',
    importer.includes('put("sha256"') && importer.includes('put("importedAt"'))

  const contract = read('app/services/native/inferencePlugin.ts')
  ok('TS exposes sha256 on the import result', /sha256\?:\s*string/.test(contract))
  ok('TS exposes importedAt', /importedAt\?:\s*number/.test(contract))
}

// =====================================================================
section('15. The tensor shape is declared, not left to a default')
{
  // The runtime builds its ONNX tensor from the DESCRIPTOR's shape. An
  // imported model defaults to [-1], which the runtime would resolve
  // by dividing the element count — producing the wrong rank rather
  // than an error. So the shape must always be made concrete.
  //
  // Which concrete shape is correct is now decided by section 17 from
  // the graph itself, not hardcoded here.
  ok('the session declares a concrete shape from the contract',
    sessionSrc.includes('predicted.concreteInputShape()'))
  ok('it can declare LOG_MEL_SPECTROGRAM',
    sessionSrc.includes('InputFormat.LOG_MEL_SPECTROGRAM'))
  ok('it can declare RAW_WAVEFORM',
    sessionSrc.includes('InputFormat.RAW_WAVEFORM'))
  ok('an undeterminable format stays fully dynamic',
    /InputKind\.UNKNOWN -> InputFormat\.RAW_TENSOR/.test(sessionSrc))
  ok('it declares the CLAP sample rate',
    sessionSrc.includes('sampleRate = frontEndSampleRate'))
  ok('the tensor layout is time-major',
    frontEndSrc.includes('fun toNchwTimeMajor'))

  // For the LOG-MEL path only: 480000/480 + 1 = 1001 frames x 64 mels.
  const frames = 480000 / 480 + 1
  ok('log-mel frame count arithmetic is 1001', frames === 1001)
  ok('log-mel tensor element count is 64064', frames * 64 === 64064)
  // And the waveform path submits the samples themselves.
  ok('waveform element count is 480000', 480000 === 48000 * 10)

  // The decoder must be asked for 48 kHz, not the DSP default 22050.
  ok('the session decodes at the model rate',
    sessionSrc.includes('targetSampleRate = frontEndSampleRate'))
  ok('the source rate is reported separately from the decoded rate',
    sessionSrc.includes('put("sourceSampleRate", info.sourceSampleRate)') &&
    sessionSrc.includes('put("audioSampleRate", frontEndSampleRate)'))
}

// =====================================================================
section('16. Quality-lab compatibility is not disturbed (§6)')
{
  // Phase 20 fixed pair identity. Nothing in this phase may regress it.
  const mapping = read('app/services/ai-lab/reportMapping.ts')
  ok('canonical pair ids still present', mapping.includes('trackIdA'))
  ok('the labelled lab still uses the mapper',
    read('app/pages/dev/ai-benchmark/labeled.vue')
      .includes("from '~/services/ai-lab/reportMapping'"))
  ok('CLAP did not fork a new lab system',
    !read('app/pages/dev/ai-benchmark/clap.vue').includes('pairResults'))
}


// =====================================================================
section('17. The input format is DERIVED from the graph, not assumed')
{
  // THE FAILURE THIS PREVENTS
  // -------------------------
  // muzaiten/clap-htsat-base-onnx/audio.onnx takes [batch, 480000] raw
  // waveform and computes its mel INTERNALLY. Feeding it a
  // [1,1,1001,64] log-mel would not throw: 64064 floats would be
  // accepted by a dynamic axis, read as audio samples, and returned as
  // a finite, L2-normalised, meaningless 512-d vector. Every cosine
  // and AUC downstream would be noise.

  // The exact target model.
  const target = derive(
    [{ name: 'waveform', shape: [-1, 480000], type: 'FLOAT' }],
    [{ name: 'embedding', shape: [-1, 512], type: 'FLOAT' }],
  )
  ok('audio.onnx is detected as WAVEFORM', target.kind === 'WAVEFORM')
  ok('audio.onnx window is 480000 samples', target.samples === 480000)
  ok('audio.onnx shape is [1,480000]',
    JSON.stringify(target.concrete) === '[1,480000]')
  ok('audio.onnx embedding dim is 512', target.embed === 512)

  // The raw HTSAT tower must still take the log-mel path.
  const logmel = derive(
    [{ name: 'input', shape: [1, 1, 1001, 64], type: 'FLOAT' }],
    [{ name: 'o', shape: [1, 512], type: 'FLOAT' }],
  )
  ok('a rank-4 input is detected as LOG_MEL', logmel.kind === 'LOG_MEL')
  ok('log-mel shape is preserved',
    JSON.stringify(logmel.concrete) === '[1,1,1001,64]')
  ok('log-mel keeps 64 bins', logmel.mels === 64)

  // A rank-3 log-mel (no channel axis) is still a log-mel.
  ok('a rank-3 input is LOG_MEL',
    derive([{ name: 'i', shape: [1, 1001, 64], type: 'FLOAT' }],
      [{ name: 'o', shape: [1, 512], type: 'FLOAT' }]).kind === 'LOG_MEL')

  // Dynamic axes fall back to the LAION clip length.
  const dyn = derive(
    [{ name: 'w', shape: [-1, -1], type: 'FLOAT' }],
    [{ name: 'o', shape: [-1, 512], type: 'FLOAT' }],
  )
  ok('a fully dynamic rank-2 input defaults to 10 s at 48 kHz',
    dyn.kind === 'WAVEFORM' && dyn.samples === 480000)

  // Anything inconclusive must be UNKNOWN, never a guess.
  ok('rank 1 is UNKNOWN',
    derive([{ name: 'x', shape: [-1], type: 'FLOAT' }],
      [{ name: 'o', shape: [1, 512], type: 'FLOAT' }]).kind === 'UNKNOWN')
  ok('an implausibly short rank-2 input is UNKNOWN',
    derive([{ name: 'x', shape: [1, 3], type: 'FLOAT' }],
      [{ name: 'o', shape: [1, 512], type: 'FLOAT' }]).kind === 'UNKNOWN')
  ok('an implausibly wide mel axis is UNKNOWN',
    derive([{ name: 'x', shape: [1, 1, 10, 4096], type: 'FLOAT' }],
      [{ name: 'o', shape: [1, 512], type: 'FLOAT' }]).kind === 'UNKNOWN')
  ok('a graph with no inputs is UNKNOWN',
    derive([], [{ name: 'o', shape: [1, 512], type: 'FLOAT' }]).kind === 'UNKNOWN')
  ok('a graph with no outputs is UNKNOWN',
    derive([{ name: 'w', shape: [1, 480000], type: 'FLOAT' }], []).kind === 'UNKNOWN')

  // ---- the Kotlin must agree with the port ----
  ok('Kotlin defines the same clip length',
    /EXPECTED_WAVEFORM_SAMPLES\s*=\s*480_000/.test(contractSrc))
  ok('Kotlin uses the same short-waveform floor',
    /MIN_WAVEFORM_SAMPLES\s*=\s*8_000/.test(contractSrc))
  ok('Kotlin branches on rank 2', /rank == 2/.test(contractSrc))
  ok('Kotlin branches on rank 3 or 4', /rank == 3 \|\| rank == 4/.test(contractSrc))
  ok('Kotlin refuses an implausibly wide mel axis', /melAxis > 512/.test(contractSrc))

  // ---- the adapter must actually USE the branch ----
  ok('the adapter feeds raw samples to a waveform graph',
    /InputKind\.WAVEFORM -> windowPcm/.test(adapterSrc))
  ok('the adapter computes log-mel only for a log-mel graph',
    /else -> frontEnd\.toNchwTimeMajor\(frontEnd\.logMel\(windowPcm\)\)/.test(adapterSrc))
  ok('the adapter refuses to infer on an UNKNOWN contract',
    /InputKind\.UNKNOWN[\s\S]{0,300}Refusing to run inference/.test(adapterSrc))
  ok('the contract is derived from the LIVE graph at load',
    /ClapGraphContract\.derive\(info\.inputs, info\.outputs\)/.test(adapterSrc))
  ok('the contract is cleared on unload',
    /graphContract = null/.test(adapterSrc))
  ok('the reported input type follows the contract',
    /InputKind\.WAVEFORM -> "waveform"/.test(adapterSrc))

  // ---- the session must not force a log-mel shape ----
  ok('the session no longer hardcodes a 4-D shape',
    !/inputShape = listOf\(1L, 1L, frames\.toLong\(\)/.test(sessionSrc))
  ok('the session declares the derived format',
    /InputKind\.WAVEFORM -> InputFormat\.RAW_WAVEFORM/.test(sessionSrc))
  ok('the session reloads when the live graph disagrees',
    /RELOAD_WITH_GRAPH_SHAPE/.test(sessionSrc))
  ok('the first session is released before reloading',
    /RELOAD_WITH_GRAPH_SHAPE[\s\S]{0,600}model\.unload\(\)/.test(sessionSrc))
}

// =====================================================================
section('18. Short audio is padded the way the reference pads it')
{
  // LAION-CLAP infers with data_filling="repeatpad" (hook.py:146,183):
  // whole copies of the clip, then a ZERO tail. Not reflect, and not
  // all-silence. Both alternatives feed the model a distribution it
  // was never trained on.
  ok('fitToClip repeats whole copies',
    /repeat\(repeats\)[\s\S]{0,200}System\.arraycopy/.test(frontEndSrc))
  ok('the remainder is left as zeros',
    /Remainder stays zero/.test(frontEndSrc))
  ok('the reference rule is cited', frontEndSrc.includes('repeatpad'))
  ok('fitToClip truncates when too long',
    /pcm\.size > target\) return pcm\.copyOf\(target\)/.test(frontEndSrc))
  ok('short audio is no longer reflect-padded into the clip',
    !/for \(i in 0 until target\) out\[i\] = reflectSample/.test(frontEndSrc))
  // reflectSample must survive for STFT centre padding, which is a
  // different thing entirely.
  ok('reflect padding is still used for the STFT frame',
    /frame\[i\] = reflectSample/.test(frontEndSrc))
}

// =====================================================================
section('19. Validation reports the real graph contract (§2)')
{
  for (const c of [
    'input name', 'input dtype is float32', 'input rank',
    'input dimensions resolved', 'output name', 'output dimension',
  ]) {
    ok(`validates "${c}"`, adapterSrc.includes(`"${c}"`))
  }
  ok('an undeterminable format fails validation',
    /input format determined from graph[\s\S]{0,400}ok = false/.test(adapterSrc))
  const page = read('app/pages/dev/ai-benchmark/clap.vue')
  ok('the UI shows the derived contract', page.includes('MODEL CONTRACT'))
  ok('the UI shows the input shape', page.includes('INPUT SHAPE'))
  ok('the UI shows NORMALIZED', page.includes('NORMALIZED'))
  ok('the UI explains an internal-mel graph',
    page.includes('computes its own mel spectrogram'))
}

// =====================================================================
section('20. Window budget arithmetic (the 60 s -> 35 s bug)')
{
  const R = 48000
  const CLIP = 10 * R
  const STRIDE = 5 * R

  // THE SHIPPED BUG
  // ---------------
  // The previous build ran a fixed 6 windows and reported "60.0 s".
  // Six windows at a 5 s stride start at 0/5/10/15/20/25 and the last
  // ends at 35 s. It embedded 35 s and decoded 60 s, discarding 25 s.
  ok('6 windows cover 35 s, not 60 s', coverageSec(6, CLIP, STRIDE, R) === 35)

  // The budget must be derived from the requested duration.
  ok('10 s needs 1 window', windowBudget(10, CLIP, STRIDE, R) === 1)
  ok('30 s needs 5 windows', windowBudget(30, CLIP, STRIDE, R) === 5)
  ok('60 s needs 11 windows', windowBudget(60, CLIP, STRIDE, R) === 11)
  ok('full track has no budget', windowBudget(0, CLIP, STRIDE, R) === null)

  // And each budget must cover exactly what was asked for.
  for (const d of [10, 30, 60]) {
    const b = windowBudget(d, CLIP, STRIDE, R)!
    ok(`${d} s budget covers exactly ${d} s`,
      coverageSec(b, CLIP, STRIDE, R) === d,
      `got ${coverageSec(b, CLIP, STRIDE, R)}`)
  }

  // Sub-window requests must not produce zero or negative windows.
  ok('a 5 s request still runs 1 window', windowBudget(5, CLIP, STRIDE, R) === 1)
  ok('a 1 s request still runs 1 window', windowBudget(1, CLIP, STRIDE, R) === 1)
}

// =====================================================================
section('21. Streaming covers the track without gaps or duplication')
{
  const R = 48000
  const CLIP = 10 * R
  const STRIDE = 5 * R

  // A 290 s track (the user's 4:50) in full-track mode.
  const full = runStream(290 * R, CLIP, STRIDE, null)
  ok('a 290 s track yields 57 windows', full.windows === 57, `got ${full.windows}`)
  ok('the last window ends at the end of the track',
    full.starts.at(-1)! + CLIP === 290 * R)
  ok('the first window starts at 0', full.starts[0] === 0)

  // No gaps: consecutive starts differ by exactly one stride.
  let gapFree = true
  for (let i = 1; i < full.starts.length; i++) {
    if (full.starts[i]! - full.starts[i - 1]! !== STRIDE) gapFree = false
  }
  ok('windows advance by exactly one stride, leaving no gap', gapFree)

  // No duplication: every start is distinct.
  ok('no window is embedded twice',
    new Set(full.starts).size === full.starts.length)

  // A capped run must stop early rather than decode-and-discard.
  const capped = runStream(290 * R, CLIP, STRIDE, 11)
  ok('a capped run stops at its budget', capped.windows === 11)
  ok('a capped run only consumes what it covers',
    capped.seen === 60 * R, `saw ${capped.seen / R} s`)

  // Short audio: one padded window, not zero.
  const short = runStream(7 * R, CLIP, STRIDE, null)
  ok('a 7 s track still produces one window', short.windows === 1)
  ok('a 7 s track consumes only 7 s', short.seen === 7 * R)

  // A track shorter than the stride must not loop forever or re-embed.
  const tiny = runStream(1 * R, CLIP, STRIDE, null)
  ok('a 1 s track produces exactly one window', tiny.windows === 1)

  // Exactly one window long: no spurious trailing partial.
  const exact = runStream(10 * R, CLIP, STRIDE, null)
  ok('a track of exactly one window produces one window',
    exact.windows === 1, `got ${exact.windows}`)

  // Chunk size must not change the result.
  for (const chunk of [512, 4096, 8192, 65536]) {
    const r = runStream(60 * R, CLIP, STRIDE, null, chunk)
    ok(`chunk size ${chunk} yields the same window count`, r.windows === 11,
      `got ${r.windows}`)
  }

  // PEAK MEMORY IS INDEPENDENT OF TRACK LENGTH — the whole point.
  const short2 = runStream(30 * R, CLIP, STRIDE, null)
  const long2 = runStream(3600 * R, CLIP, STRIDE, null)
  ok('peak buffer is one window regardless of track length',
    short2.peakBufferSamples === long2.peakBufferSamples &&
    long2.peakBufferSamples === CLIP)
  ok('a one-hour track needs only a 1.9 MB window buffer',
    (long2.peakBufferSamples * 4) / 1e6 < 2)
}

// =====================================================================
section('22. Full-track mode is bounded-memory by construction')
{
  // The old path accumulated every decoded chunk into an ArrayList and
  // then concatenated it — 56 MB of PCM for a 4:50 track, ~112 MB at
  // peak during the copy. That must be gone.
  ok('the session no longer accumulates decoded chunks',
    !/val chunks = ArrayList<FloatArray>/.test(sessionSrc))
  ok('the session no longer concatenates the whole track',
    !/System\.arraycopy\(c, 0, pcm, off, c\.size\)/.test(sessionSrc))
  ok('the session no longer allocates a full-track PCM array',
    !/val pcm = FloatArray\(totalSamples\)/.test(sessionSrc))

  // It must stream instead.
  ok('the session opens a streaming embedder', /\bmodel\.openStream\(/.test(sessionSrc))
  ok('chunks cross a RENDEZVOUS channel',
    /Channel<FloatArray>\(Channel\.RENDEZVOUS\)/.test(sessionSrc))
  ok('back-pressure is explained', /back-pressure/.test(sessionSrc))
  ok('the decoder runs as a separate producer', /val producer = launch/.test(sessionSrc))
  // The channel is cancelled rather than the producer coroutine: the
  // producer may be parked on a rendezvous send, and cancelling it
  // there would race with reading its SourceInfo.
  ok('the stream is torn down once saturated',
    /channel\.cancel\(\)/.test(sessionSrc))
  ok('the producer is always joined', /producer\.join\(\)/.test(sessionSrc))
  ok('the race is documented',
    /parked\s+on\s+a\s+rendezvous\s+send/.test(sessionSrc.replace(/\/\/\s*/g, ' ')))

  // A capped run CANCELS the decoder on purpose. PcmDecoder signals
  // cancellation by throwing CANCELLED, so treating that as an error
  // would make every 10/30/60 s test fail.
  ok('cancellation is treated as success, not failure',
    /if \(e\.code != AudioAnalysisException\.Code\.CANCELLED\) throw e/.test(sessionSrc))
  ok('the reason is documented', /STOPPING EARLY IS SUCCESS/.test(sessionSrc))
  ok('a closed channel is also expected',
    /ClosedSendChannelException/.test(sessionSrc))
  // A cancelled decode never returns SourceInfo, so duration comes
  // from a header-only probe rather than being reported as unknown.
  ok('source metadata survives cancellation',
    /\.probe\(Uri\.parse\(uri\)\)/.test(sessionSrc))
  ok('the decoder exposes a header-only probe',
    /fun probe\(uri: Uri\): SourceInfo/.test(
      read('android/app/src/main/java/com/systema/music/analysis/decode/PcmDecoder.kt')))
  ok('probe starts no codec',
    !/MediaCodec/.test(
      read('android/app/src/main/java/com/systema/music/analysis/decode/PcmDecoder.kt')
        .split('fun probe(uri: Uri): SourceInfo')[1]!.split('fun decode(')[0]!))

  // No runBlocking inside a suspend function: that risks deadlocking
  // the very dispatcher inference needs.
  // Careful: the word appears in the comment explaining why it is
  // avoided, so match a CALL (runBlocking {) rather than the word.
  ok('no runBlocking call in the session', !/runBlocking\s*\{/.test(sessionSrc))
  ok('the deadlock risk is documented', /runBlocking from inside the callback/.test(sessionSrc))

  // The streaming embedder itself must hold one window and one sum.
  ok('the embedder holds exactly one window buffer',
    /private val window = FloatArray\(clip\)/.test(adapterSrc))
  ok('the embedder accumulates into a single running sum',
    /private var sum: DoubleArray\? = null/.test(adapterSrc))
  ok('the embedder retains no per-window embeddings',
    !/embeddings\.add|windowVectors|allEmbeddings/.test(adapterSrc))
  ok('the embedder slides rather than reallocating',
    /System\.arraycopy\(window, stride, window, 0, overlap\)/.test(adapterSrc))
  ok('full-track mode is an unbounded budget, not a huge buffer',
    /maxWindows: Int\?/.test(adapterSrc))

  // Pooling must be shared so streamed and array paths cannot diverge.
  ok('pooling is shared between both paths',
    /fun poolAndNormalise/.test(adapterSrc))
  ok('window length is shared between both paths',
    /fun windowLengthFor/.test(adapterSrc) &&
    /val clip = windowLengthFor\(contract\)/.test(adapterSrc))
}

// =====================================================================
section('23. Duration is selectable and reported honestly')
{
  ok('the session takes a duration', /durationSec: Int\?/.test(sessionSrc))
  ok('the default is 60 s', /DEFAULT_DURATION_SEC = 60/.test(sessionSrc))
  ok('0 means full track', /durationSec == null \|\| durationSec <= 0/.test(sessionSrc))
  ok('the choices are 10/30/60/full',
    /DURATION_CHOICES = listOf\(10, 30, 60, 0\)/.test(sessionSrc))
  ok('the plugin accepts durationSec', /call\.getInt\("durationSec"\)/.test(pluginSrc))
  ok('an absent duration falls back to the safe default',
    /\?: ClapSession\.DEFAULT_DURATION_SEC/.test(pluginSrc))

  // The reported duration must be what was EMBEDDED, not decoded.
  ok('processed duration is reported', /put\("processedDurationSec"/.test(sessionSrc))
  ok('source duration is reported', /put\("sourceDurationSec"/.test(sessionSrc))
  ok('full-track mode is flagged', /put\("fullTrack"/.test(sessionSrc))
  ok('audioDurationSec now reports embedded audio, not decoded',
    /put\("audioDurationSec", processedSec\)/.test(sessionSrc))
  ok('the overlap relationship is explained to the user',
    sessionSrc.includes('"coverageNote"'))

  const page = read('app/pages/dev/ai-benchmark/clap.vue')
  ok('the UI offers a duration selector', page.includes('AUDIO DURATION'))
  ok('the UI offers FULL TRACK', page.includes('FULL TRACK'))
  ok('the UI shows processed vs source', page.includes('AUDIO PROCESSED'))
  ok('the UI states windows overlap 50%', /overlap by 50%/.test(page))
  ok('the UI shows the window stride', page.includes('windowStrideSec'))
  ok('the button names the chosen duration',
    /TEST ONE TRACK — /.test(page))
  ok('full track is not the default',
    page.includes('CLAP_DEFAULT_DURATION_SEC'))
}

// =====================================================================
section('24. Declared tensor shape must match the supplied buffer')
{
  // THE REPORTED FAILURE, EXACTLY:
  //   "Shape [28, 480000], requires 13440000 elements but the buffer
  //    has 13840300 elements."
  // 13,840,300 samples is 288.34 s at 48 kHz — the WHOLE track. The
  // labelled lab submitted it as a single tensor, and resolveShape
  // divided 13840300 / 480000 = 28, discarding 400,300 samples.
  const FAILING = 13_840_300

  ok('the failing buffer is the whole 288.34 s track',
    Math.abs(FAILING / 48000 - 288.34) < 0.01)

  // THE REGRESSION TEST THE USER ASKED FOR: a declared element count
  // that differs from the buffer length must FAIL, not be rounded.
  let threw = false
  try {
    resolveShape([-1, 480000], FAILING)
  } catch (e) {
    threw = e instanceof ShapeMismatchError
  }
  ok('an inexact division is refused, not truncated', threw)

  // And it must not silently produce the old wrong answer.
  let produced: number[] | null = null
  try {
    produced = resolveShape([-1, 480000], FAILING)
  } catch { /* expected */ }
  ok('[28, 480000] is never returned for this buffer', produced === null)

  // Exact multiples still resolve normally.
  const exact = resolveShape([-1, 480000], 28 * 480000)
  ok('an exact multiple still resolves', JSON.stringify(exact) === '[28,480000]')
  ok('the resolved shape accounts for every element',
    elementCount(exact) === 28 * 480000)

  // A single window, the shape CLAP actually receives.
  const one = resolveShape([-1, 480000], 480000)
  ok('one window resolves to [1, 480000]', JSON.stringify(one) === '[1,480000]')
  ok('one window accounts for every element', elementCount(one) === 480000)

  // THE GENERAL INVARIANT, swept: for any buffer and any fixed
  // trailing dim, either the shape covers the buffer exactly or the
  // call throws. It must never return a shape that covers less.
  let violations = 0
  for (const fixed of [480000, 16000, 1024, 64]) {
    for (const extra of [0, 1, 7, 999, 400300]) {
      const n = fixed * 3 + extra
      try {
        const shp = resolveShape([-1, fixed], n)
        if (elementCount(shp) !== n) violations++
      } catch (e) {
        if (!(e instanceof ShapeMismatchError)) violations++
        if (extra === 0) violations++ // exact cases must NOT throw
      }
    }
  }
  ok('shape always covers the buffer exactly, or throws', violations === 0,
    `${violations} violation(s)`)

  // Fully dynamic and fully fixed shapes are unaffected.
  ok('a fully fixed shape passes through',
    JSON.stringify(resolveShape([1, 480000], 480000)) === '[1,480000]')
  ok('multiple dynamic axes fall back to a flat vector',
    JSON.stringify(resolveShape([-1, -1], 1234)) === '[1234]')
}

// =====================================================================
section('25. The labelled lab windows fixed-input models')
{
  // The root cause was architectural: the labelled evaluator was
  // written for YAMNet, whose graph takes a whole clip and returns
  // [frames, dim]. CLAP's audio.onnx takes exactly 480000 samples per
  // call, so a whole track cannot be one tensor.
  const lab = read(`${KOTLIN}/LabeledQualityLab.kt`)

  ok('the lab detects a fixed-length waveform input',
    /fun fixedWindowSamplesFor/.test(lab))
  ok('the lab has a windowed embedding path',
    /suspend fun embedByWindows/.test(lab))
  ok('the windowed path is taken before single-tensor prepare',
    lab.indexOf('fixedWindowSamplesFor(descriptor)') <
      lab.indexOf('ModelInputPreparer.prepare(pcm'))
  ok('every window tensor is exactly the declared length',
    /val window = FloatArray\(windowSamples\)/.test(lab))
  ok('windows overlap 50%', /val stride = \(windowSamples \/ 2\)/.test(lab))
  ok('one running sum, not a list of embeddings',
    /var sum: DoubleArray\? = null/.test(lab) &&
    !/embeddings\.add\(vec\)/.test(lab))
  ok('the pooled vector is L2 normalised', /preNormL2/.test(lab))
  ok('a per-window failure names the offset',
    /Window \$\{windows \+ 1\} \(offset \$start/.test(lab))
  ok('cancellation is honoured mid-track',
    /cancelRequested\.get\(\)[\s\S]{0,200}Stopped after \$windows window/.test(lab))

  // The YAMNet path must be untouched.
  ok('the frame-embedding path still exists',
    /result\.embeddingFrames/.test(lab))
  ok('YAMNet still uses FrameEmbeddingAggregator',
    /FrameEmbeddingAggregator\.aggregate\(/.test(lab))

  // Detection must be precise: only rank-2 fixed waveforms.
  ok('a dynamic-length waveform is NOT windowed',
    fixedWindowSamplesFor([-1, -1], 'RAW_WAVEFORM') === null)
  ok('a log-mel input is NOT windowed',
    fixedWindowSamplesFor([1, 1, 1001, 64], 'LOG_MEL_SPECTROGRAM') === null)
  ok('a rank-4 waveform claim is NOT windowed',
    fixedWindowSamplesFor([1, 1, 1001, 64], 'RAW_WAVEFORM') === null)
  ok('an implausibly short fixed dim is NOT windowed',
    fixedWindowSamplesFor([-1, 512], 'RAW_WAVEFORM') === null)
  ok('CLAP audio.onnx IS windowed',
    fixedWindowSamplesFor([-1, 480000], 'RAW_WAVEFORM') === 480000)

  // The failing track must now produce the geometry the device already
  // verified in the single-track test: 57 windows.
  const lengths = windowLengths(13_840_300, 480000)
  ok('the failing track yields 57 windows', lengths.length === 57,
    `got ${lengths.length}`)
  ok('every submitted tensor is exactly 480000 samples',
    lengths.every(l => l === 480000))
  ok('this matches the verified single-track result', lengths.length === 57)

  // Each individual window resolves cleanly — the original error is
  // impossible by construction now.
  let allResolve = true
  for (const l of lengths) {
    try {
      if (elementCount(resolveShape([-1, 480000], l)) !== l) allResolve = false
    } catch { allResolve = false }
  }
  ok('every window resolves to a shape matching its buffer', allResolve)

  // Short tracks still produce one full window, not a partial tensor.
  const shortT = windowLengths(3 * 48000, 480000)
  ok('a 3 s track still submits one full 480000-sample window',
    shortT.length === 1 && shortT[0] === 480000)

  // SAMPLE RATE. The lab defaulted to AudioAnalysisConfig()'s 22050 Hz,
  // inherited from the Phase 13 analyser. At that rate a 480000-sample
  // window is 21.8 s of audio, not 10 s — the window would be right in
  // samples and wrong in seconds.
  ok('the lab decodes at the model\'s declared rate',
    /targetSampleRate = descriptor\.inputSampleRate/.test(lab))
  ok('a bare AudioAnalysisConfig() no longer feeds the decoder',
    !/val config = AudioAnalysisConfig\(\)\s*\n\s*val decoder/.test(lab))
  ok('480000 samples is 10 s only at 48 kHz',
    Math.abs(480000 / 48000 - 10) < 1e-9 &&
    Math.abs(480000 / 22050 - 21.77) < 0.01)
}

// =====================================================================
section('26. The runtime refuses inexact shapes everywhere')
{
  const rtSrc = read(`${KOTLIN}/OnnxInferenceRuntime.kt`)
  const norm = rtSrc.replace(/\/\/\s*/g, ' ')

  ok('resolveShape rejects a non-zero remainder',
    /actualElements(\.toLong\(\))? % known != 0L?/.test(rtSrc))
  ok('the refusal is an INPUT_SHAPE_MISMATCH',
    /INPUT_SHAPE_MISMATCH/.test(rtSrc))
  ok('the message reports the remainder', /remainder/i.test(norm))
  ok('the message reports the buffer size', /buffer/i.test(norm))
  ok('nothing is truncated to force a fit',
    !/actualElements \/ known\s*\n?\s*\}\s*$/.test(rtSrc))
  ok('a zero or negative known product is refused',
    /known <= 0/.test(rtSrc))
}

console.log(`\n${'='.repeat(60)}`)
console.log(`CLAP INFRASTRUCTURE — ${passed} passed, ${failed} failed`)
if (failed > 0) {
  console.log('\nFailures:')
  for (const f of failures) console.log(`  - ${f}`)
  process.exit(1)
}
console.log('All CLAP infrastructure tests passed.')
console.log(
  '\nNOT PROVEN HERE: that a CLAP model loads on a device, that ORT\n' +
  'accepts the tensor, that memory is released, or that the embedding\n' +
  'is meaningful. Those need a device run, which has NOT happened.',
)
